'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9151
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("PartObr"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class PartObr
    Inherits Global.System.Data.DataSet
    
    Private tablePartObr As PartObrDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("PartObr")) Is Nothing) Then
                MyBase.Tables.Add(New PartObrDataTable(ds.Tables("PartObr")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property _PartObr() As PartObrDataTable
        Get
            Return Me.tablePartObr
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As PartObr = CType(MyBase.Clone,PartObr)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("PartObr")) Is Nothing) Then
                MyBase.Tables.Add(New PartObrDataTable(ds.Tables("PartObr")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablePartObr = CType(MyBase.Tables("PartObr"),PartObrDataTable)
        If (initTable = true) Then
            If (Not (Me.tablePartObr) Is Nothing) Then
                Me.tablePartObr.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "PartObr"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DataSet5.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablePartObr = New PartObrDataTable
        MyBase.Tables.Add(Me.tablePartObr)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerialize_PartObr() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As PartObr = New PartObr
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub PartObrRowChangeEventHandler(ByVal sender As Object, ByVal e As PartObrRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class PartObrDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private _columncod_obr_apu As Global.System.Data.DataColumn
        
        Private _columndesc_obr As Global.System.Data.DataColumn
        
        Private _columnrec_typ_apu As Global.System.Data.DataColumn
        
        Private _columnnum_par_apu As Global.System.Data.DataColumn
        
        Private _columncod_par_m As Global.System.Data.DataColumn
        
        Private columnDescripcion1 As Global.System.Data.DataColumn
        
        Private columnDescripcion2 As Global.System.Data.DataColumn
        
        Private columnDescripcion3 As Global.System.Data.DataColumn
        
        Private columnMiniDescripcion As Global.System.Data.DataColumn
        
        Private columnCodigoCovenin As Global.System.Data.DataColumn
        
        Private columnPartidaTexto As Global.System.Data.DataColumn
        
        Private _columncan_ana_apu As Global.System.Data.DataColumn
        
        Private _columnren_par_apu As Global.System.Data.DataColumn
        
        Private _columncan_apr_apu As Global.System.Data.DataColumn
        
        Private _columnund_par_apu As Global.System.Data.DataColumn
        
        Private _columnpun_par_apu As Global.System.Data.DataColumn
        
        Private _columnpun_ana_apu As Global.System.Data.DataColumn
        
        Private _columnpun_adp_apu As Global.System.Data.DataColumn
        
        Private _columnptot_pr_apu As Global.System.Data.DataColumn
        
        Private _columntot_gen_apu As Global.System.Data.DataColumn
        
        Private _columntit_is_apu As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "PartObr"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _cod_obr_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columncod_obr_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _desc_obrColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columndesc_obr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _rec_typ_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columnrec_typ_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _num_par_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columnnum_par_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _cod_par_mColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columncod_par_m
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Descripcion1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDescripcion1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Descripcion2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDescripcion2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Descripcion3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDescripcion3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MiniDescripcionColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMiniDescripcion
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CodigoCoveninColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCodigoCovenin
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PartidaTextoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPartidaTexto
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _can_ana_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columncan_ana_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _ren_par_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columnren_par_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _can_apr_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columncan_apr_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _und_par_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columnund_par_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _pun_par_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columnpun_par_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _pun_ana_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columnpun_ana_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _pun_adp_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columnpun_adp_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _ptot_pr_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columnptot_pr_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _tot_gen_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columntot_gen_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property _tit_is_apuColumn() As Global.System.Data.DataColumn
            Get
                Return Me._columntit_is_apu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As PartObrRow
            Get
                Return CType(Me.Rows(index),PartObrRow)
            End Get
        End Property
        
        Public Event PartObrRowChanging As PartObrRowChangeEventHandler
        
        Public Event PartObrRowChanged As PartObrRowChangeEventHandler
        
        Public Event PartObrRowDeleting As PartObrRowChangeEventHandler
        
        Public Event PartObrRowDeleted As PartObrRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddPartObrRow(ByVal row As PartObrRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddPartObrRow( _
                    ByVal _cod_obr_apu As String,  _
                    ByVal _desc_obr As String,  _
                    ByVal _rec_typ_apu As String,  _
                    ByVal _num_par_apu As Double,  _
                    ByVal _cod_par_m As String,  _
                    ByVal Descripcion1 As String,  _
                    ByVal Descripcion2 As String,  _
                    ByVal Descripcion3 As String,  _
                    ByVal MiniDescripcion As String,  _
                    ByVal CodigoCovenin As String,  _
                    ByVal PartidaTexto As String,  _
                    ByVal _can_ana_apu As Double,  _
                    ByVal _ren_par_apu As Double,  _
                    ByVal _can_apr_apu As Double,  _
                    ByVal _und_par_apu As String,  _
                    ByVal _pun_par_apu As Double,  _
                    ByVal _pun_ana_apu As Double,  _
                    ByVal _pun_adp_apu As Double,  _
                    ByVal _ptot_pr_apu As Double,  _
                    ByVal _tot_gen_apu As Double,  _
                    ByVal _tit_is_apu As String) As PartObrRow
            Dim rowPartObrRow As PartObrRow = CType(Me.NewRow,PartObrRow)
            Dim columnValuesArray() As Object = New Object() {_cod_obr_apu, _desc_obr, _rec_typ_apu, _num_par_apu, _cod_par_m, Descripcion1, Descripcion2, Descripcion3, MiniDescripcion, CodigoCovenin, PartidaTexto, _can_ana_apu, _ren_par_apu, _can_apr_apu, _und_par_apu, _pun_par_apu, _pun_ana_apu, _pun_adp_apu, _ptot_pr_apu, _tot_gen_apu, _tit_is_apu}
            rowPartObrRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowPartObrRow)
            Return rowPartObrRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As PartObrDataTable = CType(MyBase.Clone,PartObrDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New PartObrDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me._columncod_obr_apu = MyBase.Columns("cod-obr-apu")
            Me._columndesc_obr = MyBase.Columns("desc-obr")
            Me._columnrec_typ_apu = MyBase.Columns("rec-typ-apu")
            Me._columnnum_par_apu = MyBase.Columns("num-par-apu")
            Me._columncod_par_m = MyBase.Columns("cod-par-m")
            Me.columnDescripcion1 = MyBase.Columns("Descripcion1")
            Me.columnDescripcion2 = MyBase.Columns("Descripcion2")
            Me.columnDescripcion3 = MyBase.Columns("Descripcion3")
            Me.columnMiniDescripcion = MyBase.Columns("MiniDescripcion")
            Me.columnCodigoCovenin = MyBase.Columns("CodigoCovenin")
            Me.columnPartidaTexto = MyBase.Columns("PartidaTexto")
            Me._columncan_ana_apu = MyBase.Columns("can-ana-apu")
            Me._columnren_par_apu = MyBase.Columns("ren-par-apu")
            Me._columncan_apr_apu = MyBase.Columns("can-apr-apu")
            Me._columnund_par_apu = MyBase.Columns("und-par-apu")
            Me._columnpun_par_apu = MyBase.Columns("pun-par-apu")
            Me._columnpun_ana_apu = MyBase.Columns("pun-ana-apu")
            Me._columnpun_adp_apu = MyBase.Columns("pun-adp-apu")
            Me._columnptot_pr_apu = MyBase.Columns("ptot-pr-apu")
            Me._columntot_gen_apu = MyBase.Columns("tot-gen-apu")
            Me._columntit_is_apu = MyBase.Columns("tit-is-apu")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me._columncod_obr_apu = New Global.System.Data.DataColumn("cod-obr-apu", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            Me._columncod_obr_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columncod_obr_apu")
            Me._columncod_obr_apu.ExtendedProperties.Add("Generator_UserColumnName", "cod-obr-apu")
            MyBase.Columns.Add(Me._columncod_obr_apu)
            Me._columndesc_obr = New Global.System.Data.DataColumn("desc-obr", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            Me._columndesc_obr.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columndesc_obr")
            Me._columndesc_obr.ExtendedProperties.Add("Generator_UserColumnName", "desc-obr")
            MyBase.Columns.Add(Me._columndesc_obr)
            Me._columnrec_typ_apu = New Global.System.Data.DataColumn("rec-typ-apu", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            Me._columnrec_typ_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnrec_typ_apu")
            Me._columnrec_typ_apu.ExtendedProperties.Add("Generator_UserColumnName", "rec-typ-apu")
            MyBase.Columns.Add(Me._columnrec_typ_apu)
            Me._columnnum_par_apu = New Global.System.Data.DataColumn("num-par-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columnnum_par_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnnum_par_apu")
            Me._columnnum_par_apu.ExtendedProperties.Add("Generator_UserColumnName", "num-par-apu")
            MyBase.Columns.Add(Me._columnnum_par_apu)
            Me._columncod_par_m = New Global.System.Data.DataColumn("cod-par-m", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            Me._columncod_par_m.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columncod_par_m")
            Me._columncod_par_m.ExtendedProperties.Add("Generator_UserColumnName", "cod-par-m")
            MyBase.Columns.Add(Me._columncod_par_m)
            Me.columnDescripcion1 = New Global.System.Data.DataColumn("Descripcion1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDescripcion1)
            Me.columnDescripcion2 = New Global.System.Data.DataColumn("Descripcion2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDescripcion2)
            Me.columnDescripcion3 = New Global.System.Data.DataColumn("Descripcion3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDescripcion3)
            Me.columnMiniDescripcion = New Global.System.Data.DataColumn("MiniDescripcion", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMiniDescripcion)
            Me.columnCodigoCovenin = New Global.System.Data.DataColumn("CodigoCovenin", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCodigoCovenin)
            Me.columnPartidaTexto = New Global.System.Data.DataColumn("PartidaTexto", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPartidaTexto)
            Me._columncan_ana_apu = New Global.System.Data.DataColumn("can-ana-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columncan_ana_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columncan_ana_apu")
            Me._columncan_ana_apu.ExtendedProperties.Add("Generator_UserColumnName", "can-ana-apu")
            MyBase.Columns.Add(Me._columncan_ana_apu)
            Me._columnren_par_apu = New Global.System.Data.DataColumn("ren-par-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columnren_par_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnren_par_apu")
            Me._columnren_par_apu.ExtendedProperties.Add("Generator_UserColumnName", "ren-par-apu")
            MyBase.Columns.Add(Me._columnren_par_apu)
            Me._columncan_apr_apu = New Global.System.Data.DataColumn("can-apr-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columncan_apr_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columncan_apr_apu")
            Me._columncan_apr_apu.ExtendedProperties.Add("Generator_UserColumnName", "can-apr-apu")
            MyBase.Columns.Add(Me._columncan_apr_apu)
            Me._columnund_par_apu = New Global.System.Data.DataColumn("und-par-apu", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            Me._columnund_par_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnund_par_apu")
            Me._columnund_par_apu.ExtendedProperties.Add("Generator_UserColumnName", "und-par-apu")
            MyBase.Columns.Add(Me._columnund_par_apu)
            Me._columnpun_par_apu = New Global.System.Data.DataColumn("pun-par-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columnpun_par_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnpun_par_apu")
            Me._columnpun_par_apu.ExtendedProperties.Add("Generator_UserColumnName", "pun-par-apu")
            MyBase.Columns.Add(Me._columnpun_par_apu)
            Me._columnpun_ana_apu = New Global.System.Data.DataColumn("pun-ana-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columnpun_ana_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnpun_ana_apu")
            Me._columnpun_ana_apu.ExtendedProperties.Add("Generator_UserColumnName", "pun-ana-apu")
            MyBase.Columns.Add(Me._columnpun_ana_apu)
            Me._columnpun_adp_apu = New Global.System.Data.DataColumn("pun-adp-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columnpun_adp_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnpun_adp_apu")
            Me._columnpun_adp_apu.ExtendedProperties.Add("Generator_UserColumnName", "pun-adp-apu")
            MyBase.Columns.Add(Me._columnpun_adp_apu)
            Me._columnptot_pr_apu = New Global.System.Data.DataColumn("ptot-pr-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columnptot_pr_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnptot_pr_apu")
            Me._columnptot_pr_apu.ExtendedProperties.Add("Generator_UserColumnName", "ptot-pr-apu")
            MyBase.Columns.Add(Me._columnptot_pr_apu)
            Me._columntot_gen_apu = New Global.System.Data.DataColumn("tot-gen-apu", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            Me._columntot_gen_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columntot_gen_apu")
            Me._columntot_gen_apu.ExtendedProperties.Add("Generator_UserColumnName", "tot-gen-apu")
            MyBase.Columns.Add(Me._columntot_gen_apu)
            Me._columntit_is_apu = New Global.System.Data.DataColumn("tit-is-apu", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            Me._columntit_is_apu.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columntit_is_apu")
            Me._columntit_is_apu.ExtendedProperties.Add("Generator_UserColumnName", "tit-is-apu")
            MyBase.Columns.Add(Me._columntit_is_apu)
            Me._columncod_obr_apu.MaxLength = 16
            Me._columndesc_obr.MaxLength = 54
            Me._columnrec_typ_apu.MaxLength = 2
            Me._columncod_par_m.MaxLength = 14
            Me.columnDescripcion1.MaxLength = 70
            Me.columnDescripcion2.MaxLength = 70
            Me.columnDescripcion3.MaxLength = 70
            Me.columnMiniDescripcion.MaxLength = 60
            Me.columnCodigoCovenin.MaxLength = 15
            Me.columnPartidaTexto.MaxLength = 8
            Me._columnund_par_apu.MaxLength = 3
            Me._columntit_is_apu.MaxLength = 5
            Me.ExtendedProperties.Add("Generator_TablePropName", "_PartObr")
            Me.ExtendedProperties.Add("Generator_UserTableName", "PartObr")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewPartObrRow() As PartObrRow
            Return CType(Me.NewRow,PartObrRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New PartObrRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(PartObrRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.PartObrRowChangedEvent) Is Nothing) Then
                RaiseEvent PartObrRowChanged(Me, New PartObrRowChangeEvent(CType(e.Row,PartObrRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.PartObrRowChangingEvent) Is Nothing) Then
                RaiseEvent PartObrRowChanging(Me, New PartObrRowChangeEvent(CType(e.Row,PartObrRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.PartObrRowDeletedEvent) Is Nothing) Then
                RaiseEvent PartObrRowDeleted(Me, New PartObrRowChangeEvent(CType(e.Row,PartObrRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.PartObrRowDeletingEvent) Is Nothing) Then
                RaiseEvent PartObrRowDeleting(Me, New PartObrRowChangeEvent(CType(e.Row,PartObrRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemovePartObrRow(ByVal row As PartObrRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As PartObr = New PartObr
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "PartObrDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class PartObrRow
        Inherits Global.System.Data.DataRow
        
        Private tablePartObr As PartObrDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablePartObr = CType(Me.Table,PartObrDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _cod_obr_apu() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._cod_obr_apuColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'cod-obr-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._cod_obr_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _desc_obr() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._desc_obrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'desc-obr' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._desc_obrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _rec_typ_apu() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._rec_typ_apuColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'rec-typ-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._rec_typ_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _num_par_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._num_par_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'num-par-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._num_par_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _cod_par_m() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._cod_par_mColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'cod-par-m' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._cod_par_mColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Descripcion1() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr.Descripcion1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Descripcion1' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr.Descripcion1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Descripcion2() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr.Descripcion2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Descripcion2' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr.Descripcion2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Descripcion3() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr.Descripcion3Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Descripcion3' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr.Descripcion3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MiniDescripcion() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr.MiniDescripcionColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'MiniDescripcion' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr.MiniDescripcionColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CodigoCovenin() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr.CodigoCoveninColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CodigoCovenin' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr.CodigoCoveninColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PartidaTexto() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr.PartidaTextoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PartidaTexto' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr.PartidaTextoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _can_ana_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._can_ana_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'can-ana-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._can_ana_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _ren_par_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._ren_par_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ren-par-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._ren_par_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _can_apr_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._can_apr_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'can-apr-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._can_apr_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _und_par_apu() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._und_par_apuColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'und-par-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._und_par_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _pun_par_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._pun_par_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'pun-par-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._pun_par_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _pun_ana_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._pun_ana_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'pun-ana-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._pun_ana_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _pun_adp_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._pun_adp_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'pun-adp-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._pun_adp_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _ptot_pr_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._ptot_pr_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ptot-pr-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._ptot_pr_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _tot_gen_apu() As Double
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._tot_gen_apuColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'tot-gen-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._tot_gen_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property _tit_is_apu() As String
            Get
                Try 
                    Return CType(Me(Me.tablePartObr._tit_is_apuColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'tit-is-apu' in table 'PartObr' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartObr._tit_is_apuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_cod_obr_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._cod_obr_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_cod_obr_apuNull()
            Me(Me.tablePartObr._cod_obr_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_desc_obrNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._desc_obrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_desc_obrNull()
            Me(Me.tablePartObr._desc_obrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_rec_typ_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._rec_typ_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_rec_typ_apuNull()
            Me(Me.tablePartObr._rec_typ_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_num_par_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._num_par_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_num_par_apuNull()
            Me(Me.tablePartObr._num_par_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_cod_par_mNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._cod_par_mColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_cod_par_mNull()
            Me(Me.tablePartObr._cod_par_mColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDescripcion1Null() As Boolean
            Return Me.IsNull(Me.tablePartObr.Descripcion1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDescripcion1Null()
            Me(Me.tablePartObr.Descripcion1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDescripcion2Null() As Boolean
            Return Me.IsNull(Me.tablePartObr.Descripcion2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDescripcion2Null()
            Me(Me.tablePartObr.Descripcion2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDescripcion3Null() As Boolean
            Return Me.IsNull(Me.tablePartObr.Descripcion3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDescripcion3Null()
            Me(Me.tablePartObr.Descripcion3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMiniDescripcionNull() As Boolean
            Return Me.IsNull(Me.tablePartObr.MiniDescripcionColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMiniDescripcionNull()
            Me(Me.tablePartObr.MiniDescripcionColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCodigoCoveninNull() As Boolean
            Return Me.IsNull(Me.tablePartObr.CodigoCoveninColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCodigoCoveninNull()
            Me(Me.tablePartObr.CodigoCoveninColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPartidaTextoNull() As Boolean
            Return Me.IsNull(Me.tablePartObr.PartidaTextoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPartidaTextoNull()
            Me(Me.tablePartObr.PartidaTextoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_can_ana_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._can_ana_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_can_ana_apuNull()
            Me(Me.tablePartObr._can_ana_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_ren_par_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._ren_par_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_ren_par_apuNull()
            Me(Me.tablePartObr._ren_par_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_can_apr_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._can_apr_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_can_apr_apuNull()
            Me(Me.tablePartObr._can_apr_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_und_par_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._und_par_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_und_par_apuNull()
            Me(Me.tablePartObr._und_par_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_pun_par_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._pun_par_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_pun_par_apuNull()
            Me(Me.tablePartObr._pun_par_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_pun_ana_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._pun_ana_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_pun_ana_apuNull()
            Me(Me.tablePartObr._pun_ana_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_pun_adp_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._pun_adp_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_pun_adp_apuNull()
            Me(Me.tablePartObr._pun_adp_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_ptot_pr_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._ptot_pr_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_ptot_pr_apuNull()
            Me(Me.tablePartObr._ptot_pr_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_tot_gen_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._tot_gen_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_tot_gen_apuNull()
            Me(Me.tablePartObr._tot_gen_apuColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Is_tit_is_apuNull() As Boolean
            Return Me.IsNull(Me.tablePartObr._tit_is_apuColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Set_tit_is_apuNull()
            Me(Me.tablePartObr._tit_is_apuColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class PartObrRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As PartObrRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As PartObrRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As PartObrRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class

Namespace PartObrTableAdapters
    
    '''<summary>
    '''Represents the connection and commands used to retrieve and save data.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
     Global.System.ComponentModel.ToolboxItem(true),  _
     Global.System.ComponentModel.DataObjectAttribute(true),  _
     Global.System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner"& _ 
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"),  _
     Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")>  _
    Partial Public Class PartObrTableAdapter
        Inherits Global.System.ComponentModel.Component
        
        Private WithEvents _adapter As Global.System.Data.OleDb.OleDbDataAdapter
        
        Private _connection As Global.System.Data.OleDb.OleDbConnection
        
        Private _commandCollection() As Global.System.Data.OleDb.OleDbCommand
        
        Private _clearBeforeFill As Boolean
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.ClearBeforeFill = true
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private ReadOnly Property Adapter() As Global.System.Data.OleDb.OleDbDataAdapter
            Get
                If (Me._adapter Is Nothing) Then
                    Me.InitAdapter
                End If
                Return Me._adapter
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Property Connection() As Global.System.Data.OleDb.OleDbConnection
            Get
                If (Me._connection Is Nothing) Then
                    Me.InitConnection
                End If
                Return Me._connection
            End Get
            Set
                Me._connection = value
                If (Not (Me.Adapter.InsertCommand) Is Nothing) Then
                    Me.Adapter.InsertCommand.Connection = value
                End If
                If (Not (Me.Adapter.DeleteCommand) Is Nothing) Then
                    Me.Adapter.DeleteCommand.Connection = value
                End If
                If (Not (Me.Adapter.UpdateCommand) Is Nothing) Then
                    Me.Adapter.UpdateCommand.Connection = value
                End If
                Dim i As Integer = 0
                Do While (i < Me.CommandCollection.Length)
                    If (Not (Me.CommandCollection(i)) Is Nothing) Then
                        CType(Me.CommandCollection(i),Global.System.Data.OleDb.OleDbCommand).Connection = value
                    End If
                    i = (i + 1)
                Loop
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected ReadOnly Property CommandCollection() As Global.System.Data.OleDb.OleDbCommand()
            Get
                If (Me._commandCollection Is Nothing) Then
                    Me.InitCommandCollection
                End If
                Return Me._commandCollection
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ClearBeforeFill() As Boolean
            Get
                Return Me._clearBeforeFill
            End Get
            Set
                Me._clearBeforeFill = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitAdapter()
            Me._adapter = New Global.System.Data.OleDb.OleDbDataAdapter
            Dim tableMapping As Global.System.Data.Common.DataTableMapping = New Global.System.Data.Common.DataTableMapping
            tableMapping.SourceTable = "Table"
            tableMapping.DataSetTable = "PartObr"
            tableMapping.ColumnMappings.Add("cod-obr-apu", "cod-obr-apu")
            tableMapping.ColumnMappings.Add("desc-obr", "desc-obr")
            tableMapping.ColumnMappings.Add("rec-typ-apu", "rec-typ-apu")
            tableMapping.ColumnMappings.Add("num-par-apu", "num-par-apu")
            tableMapping.ColumnMappings.Add("cod-par-m", "cod-par-m")
            tableMapping.ColumnMappings.Add("Descripcion1", "Descripcion1")
            tableMapping.ColumnMappings.Add("Descripcion2", "Descripcion2")
            tableMapping.ColumnMappings.Add("Descripcion3", "Descripcion3")
            tableMapping.ColumnMappings.Add("MiniDescripcion", "MiniDescripcion")
            tableMapping.ColumnMappings.Add("CodigoCovenin", "CodigoCovenin")
            tableMapping.ColumnMappings.Add("PartidaTexto", "PartidaTexto")
            tableMapping.ColumnMappings.Add("can-ana-apu", "can-ana-apu")
            tableMapping.ColumnMappings.Add("ren-par-apu", "ren-par-apu")
            tableMapping.ColumnMappings.Add("can-apr-apu", "can-apr-apu")
            tableMapping.ColumnMappings.Add("und-par-apu", "und-par-apu")
            tableMapping.ColumnMappings.Add("pun-par-apu", "pun-par-apu")
            tableMapping.ColumnMappings.Add("pun-ana-apu", "pun-ana-apu")
            tableMapping.ColumnMappings.Add("pun-adp-apu", "pun-adp-apu")
            tableMapping.ColumnMappings.Add("ptot-pr-apu", "ptot-pr-apu")
            tableMapping.ColumnMappings.Add("tot-gen-apu", "tot-gen-apu")
            tableMapping.ColumnMappings.Add("tit-is-apu", "tit-is-apu")
            Me._adapter.TableMappings.Add(tableMapping)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitConnection()
            Me._connection = New Global.System.Data.OleDb.OleDbConnection
            Me._connection.ConnectionString = Global.APP2020.My.MySettings.Default.MasterAPVConnectionString
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitCommandCollection()
            Me._commandCollection = New Global.System.Data.OleDb.OleDbCommand(0) {}
            Me._commandCollection(0) = New Global.System.Data.OleDb.OleDbCommand
            Me._commandCollection(0).Connection = Me.Connection
            Me._commandCollection(0).CommandText = "SELECT        [cod-obr-apu], [desc-obr], [rec-typ-apu], [num-par-apu], [cod-par-m"& _ 
                "], Descripcion1, Descripcion2, Descripcion3, MiniDescripcion, CodigoCovenin, Par"& _ 
                "tidaTexto, [can-ana-apu], [ren-par-apu], [can-apr-apu], [und-par-apu], "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"       "& _ 
                "                  [pun-par-apu], [pun-ana-apu], [pun-adp-apu], [ptot-pr-apu], [t"& _ 
                "ot-gen-apu], [tit-is-apu]"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM            PartObr"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ORDER BY [num-par-apu]"
            Me._commandCollection(0).CommandType = Global.System.Data.CommandType.Text
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.Fill, true)>  _
        Public Overloads Overridable Function Fill(ByVal dataTable As PartObr.PartObrDataTable) As Integer
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            If (Me.ClearBeforeFill = true) Then
                dataTable.Clear
            End If
            Dim returnValue As Integer = Me.Adapter.Fill(dataTable)
            Return returnValue
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter"),  _
         Global.System.ComponentModel.DataObjectMethodAttribute(Global.System.ComponentModel.DataObjectMethodType.[Select], true)>  _
        Public Overloads Overridable Function GetData() As PartObr.PartObrDataTable
            Me.Adapter.SelectCommand = Me.CommandCollection(0)
            Dim dataTable As PartObr.PartObrDataTable = New PartObr.PartObrDataTable
            Me.Adapter.Fill(dataTable)
            Return dataTable
        End Function
    End Class
End Namespace
